# Generated by Django 2.1.7 on 2019-02-21 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='tag',
            new_name='tags',
        ),
        migrations.AddField(
            model_name='customer',
            name='status',
            field=models.SmallIntegerField(choices=[(0, '转介绍'), (1, 'qq群'), (2, '官网'), (3, '百度'), (4, '市场推销'), (5, '知乎')], default=1),
        ),
    ]
